apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: notificaciones-failure
spec:
  action: pod-failure
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: microservicio-notificaciones
  duration: '30s'
  scheduler:
    cron: '@every 2m'
