apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: microservicio-notificaciones-fault-delay
spec:
  hosts:
  - microservicio-notificaciones
  http:
  - fault:
      delay:
        percentage:
          value: 50.0  # 50% de las peticiones tendr√°n delay
        fixedDelay: 5s  # Delay de 5 segundos
    route:
    - destination:
        host: microservicio-notificaciones
        port:
          number: 5001
