apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: microservicio-notificaciones-fault-abort
spec:
  hosts:
  - microservicio-notificaciones
  http:
  - fault:
      abort:
        percentage:
          value: 30.0  # 30% de las peticiones fallar√°n
        httpStatus: 503  # Service Unavailable
    route:
    - destination:
        host: microservicio-notificaciones
        port:
          number: 5001
