apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: microservicio-notificaciones-fault-combined
spec:
  hosts:
  - microservicio-notificaciones
  http:
  - fault:
      delay:
        percentage:
          value: 30.0  # 30% tendrá delay
        fixedDelay: 3s
      abort:
        percentage:
          value: 20.0  # 20% fallará con 503
        httpStatus: 503
    route:
    - destination:
        host: microservicio-notificaciones
        port:
          number: 5001
