apiVersion: v1
kind: Service
metadata:
  name: microservicio-notificaciones
spec:
  selector:
    app: microservicio-notificaciones
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-notificaciones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservicio-notificaciones
  template:
    metadata:
      labels:
        app: microservicio-notificaciones
    spec:
      containers:
      - name: microservicio-notificaciones
        image: microservicio-notificaciones:latest
        ports:
        - containerPort: 5001
        readinessProbe:
          httpGet:
            path: /notificar
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /notificar
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 10
