apiVersion: v1
kind: Service
metadata:
  name: microservicio-usuarios
spec:
  selector:
    app: microservicio-usuarios
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-usuarios
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservicio-usuarios
  template:
    metadata:
      labels:
        app: microservicio-usuarios
    spec:
      containers:
      - name: microservicio-usuarios
        image: microservicio-usuarios:latest
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /usuarios
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /usuarios
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
